name: GitOps Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f manifests/

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install my-app charts/app
